version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - '3000:3000'
  site:
    build:
      context: .
      dockerfile: frontend/site/Dockerfile
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
  survey:
    build:
      context: .
      dockerfile: frontend/survey/Dockerfile
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
  onboarding:
    build:
      context: .
      dockerfile: frontend/RealtorInterface/Onboarding/Dockerfile
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
  leadreports:
    build:
      context: .
      dockerfile: frontend/RealtorInterface/LeadReports/Dockerfile
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
