version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - '3000:3000'
  site:
    build:
      context: .
      dockerfile: frontend/site/Dockerfile
    depends_on:
      - api
    ports:
      - '4173:80'
  survey:
    build:
      context: .
      dockerfile: frontend/survey/Dockerfile
    depends_on:
      - api
    ports:
      - '4174:80'
  onboarding:
    build:
      context: .
      dockerfile: frontend/RealtorInterface/Onboarding/Dockerfile
    depends_on:
      - api
    ports:
      - '4175:80'
  leadreports:
    build:
      context: .
      dockerfile: frontend/RealtorInterface/LeadReports/Dockerfile
    depends_on:
      - api
    ports:
      - '4176:80'
