version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - '3000:3000'
  site:
    build:
      context: .
      dockerfile: frontend/site/Dockerfile
    depends_on:
      - backend
    ports:
      - '4173:80'
  survey:
    build:
      context: .
      dockerfile: frontend/survey/Dockerfile
    depends_on:
      - backend
    ports:
      - '4174:80'
