on: { push: { branches: [pt-BR] } }
jobs:
  deploy:
    runs-on: ubuntu-latest

        
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}


    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP_PT_BR }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}

          envs: SUPABASE_URL,SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY

          script: |
            set -e
            
            export VITE_SUPABASE_URL="$SUPABASE_URL"
            export VITE_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"

            cd /home/Lead

            git fetch --all --prune
            git checkout pt-BR
            git reset --hard origin/pt-BR

            docker compose down --remove-orphans
            
            docker compose build --pull --no-cache \
              --build-arg VITE_SUPABASE_URL \
              --build-arg VITE_SUPABASE_ANON_KEY

            docker compose up -d
            # Copy new host-level vhost and reload Ubuntu Nginx
            cp deploy/host-nginx/myrealvaluation.conf /etc/nginx/sites-available/
            ln -sf /etc/nginx/sites-available/myrealvaluation.conf /etc/nginx/sites-enabled/
            nginx -t
            systemctl restart nginx
