on: { push: { branches: [main] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP_pt_BR }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/Lead
            git pull
            docker compose down --remove-orphans
            docker compose build --no-cache
            docker compose up -d
            # Copy new host-level vhost and reload Ubuntu Nginx
            cp deploy/host-nginx/myrealvaluation.conf /etc/nginx/sites-available/
            ln -sf /etc/nginx/sites-available/myrealvaluation.conf /etc/nginx/sites-enabled/
            nginx -t
            systemctl restart nginx
