on:
  push:
    branches: [pt-BR]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP_PT_BR }}
          username: root
          key: ${{ secrets.SERVER_KEY_PT_BR }}

          # expose the three secrets to the remote shell
          envs: SUPABASE_URL,SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY

          script: |
            set -e

            # 1️⃣ export Vite-prefixed copies for the frontend build
            export VITE_SUPABASE_URL="$SUPABASE_URL"
            export VITE_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"

            cd /home/Lead
            git fetch --all --prune
            git checkout pt-BR
            git reset --hard origin/pt-BR

            # 2️⃣ make sure Docker sees the same vars at build-time
            export DOCKER_BUILDKIT=1
            docker compose down --remove-orphans
            docker compose build --pull \
              --build-arg VITE_SUPABASE_URL \
              --build-arg VITE_SUPABASE_ANON_KEY
            docker compose up -d

            nginx -t && nginx -s reload
