name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 30m
          script: |
            set -e
            cd /home/Lead && \
            git pull && \
            docker compose down && \
            docker compose up -d --build && \
            # Copy new host-level vhost and reload Ubuntu Nginx
            cp deploy/host-nginx/myrealvaluation.conf /etc/nginx/sites-available/ && \
            ln -sf /etc/nginx/sites-available/myrealvaluation.conf /etc/nginx/sites-enabled/ && \
            nginx -t && \
            systemctl restart nginx
